import { db } from '@/db';
import { courses } from '@/db/schema';

async function main() {
    const sampleCourses = [
        // Computer Science Department
        {
            title: 'Data Structures and Algorithms',
            code: 'CS101',
            credits: 4,
            department: 'Computer Science',
            syllabus: 'Introduction to fundamental data structures including arrays, linked lists, stacks, queues, trees, and graphs. Analysis of algorithms, time and space complexity, sorting and searching algorithms, dynamic programming, and greedy algorithms.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Advanced Algorithms',
            code: 'CS201',
            credits: 3,
            department: 'Computer Science',
            syllabus: 'Advanced algorithmic techniques including divide and conquer, graph algorithms, network flows, string algorithms, computational geometry, and approximation algorithms. NP-completeness and complexity theory.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Database Systems',
            code: 'CS301',
            credits: 4,
            department: 'Computer Science',
            syllabus: 'Database design principles, relational model, SQL, normalization, indexing, query optimization, transaction management, concurrency control, recovery systems, and distributed databases.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Web Development',
            code: 'CS401',
            credits: 3,
            department: 'Computer Science',
            syllabus: 'Full-stack web development covering HTML5, CSS3, JavaScript, React, Node.js, Express, RESTful APIs, authentication, deployment strategies, and modern web frameworks.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Artificial Intelligence and Machine Learning',
            code: 'CS501',
            credits: 4,
            department: 'Computer Science',
            syllabus: 'Introduction to AI concepts, machine learning algorithms, supervised and unsupervised learning, neural networks, deep learning, natural language processing, and computer vision applications.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Software Engineering',
            code: 'CS601',
            credits: 3,
            department: 'Computer Science',
            syllabus: 'Software development lifecycle, requirements analysis, system design, testing methodologies, version control, agile development, project management, and software quality assurance.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Computer Networks',
            code: 'CS701',
            credits: 3,
            department: 'Computer Science',
            syllabus: 'Network protocols, OSI model, TCP/IP, routing algorithms, network security, wireless networks, network programming, and distributed systems fundamentals.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        // Mathematics Department
        {
            title: 'Calculus I',
            code: 'MATH101',
            credits: 4,
            department: 'Mathematics',
            syllabus: 'Limits and continuity, derivatives and applications, optimization problems, related rates, curve sketching, antiderivatives, and the fundamental theorem of calculus.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Calculus II',
            code: 'MATH201',
            credits: 4,
            department: 'Mathematics',
            syllabus: 'Integration techniques, applications of integration, sequences and series, parametric equations, polar coordinates, and vectors in the plane.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Linear Algebra',
            code: 'MATH301',
            credits: 3,
            department: 'Mathematics',
            syllabus: 'Vector spaces, linear transformations, matrices, determinants, eigenvalues and eigenvectors, orthogonality, and applications to geometry and differential equations.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Statistics and Probability',
            code: 'MATH401',
            credits: 3,
            department: 'Mathematics',
            syllabus: 'Descriptive statistics, probability theory, random variables, probability distributions, hypothesis testing, confidence intervals, regression analysis, and statistical inference.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Discrete Mathematics',
            code: 'MATH501',
            credits: 3,
            department: 'Mathematics',
            syllabus: 'Logic and proof techniques, set theory, relations and functions, combinatorics, graph theory, number theory, and discrete probability.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            title: 'Differential Equations',
            code: 'MATH601',
            credits: 3,
            department: 'Mathematics',
            syllabus: 'First-order differential equations, higher-order linear equations, systems of differential equations, Laplace transforms, and applications to engineering and physics.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        // Physics Department
        {
            title: 'Classical Physics I',
            code: 'PHYS101',
            credits: 4,
            department: 'Physics',
            syllabus: 'Mechanics including kinematics, dynamics, energy, momentum, rotational motion, oscillations, waves, and an introduction to special relativity.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Classical Physics II',
            code: 'PHYS201',
            credits: 4,
            department: 'Physics',
            syllabus: 'Electricity and magnetism, electric fields, magnetic fields, electromagnetic induction, AC circuits, Maxwell equations, and electromagnetic waves.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Quantum Mechanics',
            code: 'PHYS301',
            credits: 4,
            department: 'Physics',
            syllabus: 'Wave-particle duality, Schrödinger equation, quantum states, operators, uncertainty principle, harmonic oscillator, hydrogen atom, and quantum measurement theory.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Thermodynamics',
            code: 'PHYS401',
            credits: 3,
            department: 'Physics',
            syllabus: 'Laws of thermodynamics, heat engines, entropy, statistical mechanics, phase transitions, and applications to physical systems.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Electromagnetism',
            code: 'PHYS501',
            credits: 4,
            department: 'Physics',
            syllabus: 'Advanced electromagnetic theory, Maxwell equations in differential form, electromagnetic waves, radiation, waveguides, and relativistic electrodynamics.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            title: 'Modern Physics',
            code: 'PHYS601',
            credits: 3,
            department: 'Physics',
            syllabus: 'Special relativity, quantum theory, atomic structure, nuclear physics, particle physics, and contemporary developments in physics research.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        // Chemistry Department
        {
            title: 'General Chemistry I',
            code: 'CHEM101',
            credits: 4,
            department: 'Chemistry',
            syllabus: 'Atomic structure, chemical bonding, molecular geometry, stoichiometry, chemical reactions, gases, thermochemistry, and periodic properties.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Organic Chemistry I',
            code: 'CHEM201',
            credits: 4,
            department: 'Chemistry',
            syllabus: 'Structure and bonding in organic molecules, nomenclature, stereochemistry, reaction mechanisms, alkanes, alkenes, alkynes, and aromatic compounds.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Organic Chemistry II',
            code: 'CHEM301',
            credits: 4,
            department: 'Chemistry',
            syllabus: 'Advanced organic reactions, carbonyl chemistry, amines, carboxylic acids, spectroscopy, synthesis strategies, and biomolecule chemistry.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Inorganic Chemistry',
            code: 'CHEM401',
            credits: 3,
            department: 'Chemistry',
            syllabus: 'Coordination compounds, crystal field theory, organometallic chemistry, solid state chemistry, bioinorganic chemistry, and advanced bonding theories.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Physical Chemistry',
            code: 'CHEM501',
            credits: 4,
            department: 'Chemistry',
            syllabus: 'Quantum chemistry, molecular spectroscopy, statistical thermodynamics, chemical kinetics, electrochemistry, and surface chemistry.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            title: 'Analytical Chemistry',
            code: 'CHEM601',
            credits: 3,
            department: 'Chemistry',
            syllabus: 'Quantitative analysis, instrumental methods, chromatography, mass spectrometry, NMR spectroscopy, and modern analytical techniques.',
            enrolledCount: 0,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        }
    ];

    await db.insert(courses).values(sampleCourses);
    
    console.log('✅ Courses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});