import { db } from '@/db';
import { faculty } from '@/db/schema';

async function main() {
    const sampleFaculty = [
        // Computer Science Department - 5 faculty
        {
            userId: 2,
            name: 'Dr. Sarah Johnson',
            email: 'sarah.johnson@university.edu',
            department: 'Computer Science',
            designation: 'Professor',
            salary: 95000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [1, 3, 7, 12],
            createdAt: new Date('2023-08-15').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 3,
            name: 'Dr. Michael Chen',
            email: 'michael.chen@university.edu',
            department: 'Computer Science',
            designation: 'Associate Professor',
            salary: 78000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [2, 8, 13],
            createdAt: new Date('2023-09-01').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 4,
            name: 'Dr. Emily Rodriguez',
            email: 'emily.rodriguez@university.edu',
            department: 'Computer Science',
            designation: 'Assistant Professor',
            salary: 62000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [4, 9, 14],
            createdAt: new Date('2023-09-15').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 5,
            name: 'Dr. James Wilson',
            email: 'james.wilson@university.edu',
            department: 'Computer Science',
            designation: 'Associate Professor',
            salary: 82000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [5, 10, 15],
            createdAt: new Date('2023-08-20').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 6,
            name: 'Ms. Lisa Thompson',
            email: 'lisa.thompson@university.edu',
            department: 'Computer Science',
            designation: 'Lecturer',
            salary: 48000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [6, 11],
            createdAt: new Date('2023-10-01').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        // Mathematics Department - 4 faculty
        {
            userId: 7,
            name: 'Dr. Robert Anderson',
            email: 'robert.anderson@university.edu',
            department: 'Mathematics',
            designation: 'Professor',
            salary: 88000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [16, 18, 20, 22],
            createdAt: new Date('2023-08-10').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 8,
            name: 'Dr. Maria Garcia',
            email: 'maria.garcia@university.edu',
            department: 'Mathematics',
            designation: 'Associate Professor',
            salary: 75000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [17, 19, 21],
            createdAt: new Date('2023-09-05').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 9,
            name: 'Dr. David Kim',
            email: 'david.kim@university.edu',
            department: 'Mathematics',
            designation: 'Assistant Professor',
            salary: 58000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [23, 24],
            createdAt: new Date('2023-09-20').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 10,
            name: 'Ms. Jennifer Lee',
            email: 'jennifer.lee@university.edu',
            department: 'Mathematics',
            designation: 'Lecturer',
            salary: 42000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [25, 26],
            createdAt: new Date('2023-10-10').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        // Physics Department - 3 faculty
        {
            userId: 11,
            name: 'Dr. Thomas Brown',
            email: 'thomas.brown@university.edu',
            department: 'Physics',
            designation: 'Professor',
            salary: 92000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [27, 29, 31],
            createdAt: new Date('2023-08-25').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 12,
            name: 'Dr. Rachel White',
            email: 'rachel.white@university.edu',
            department: 'Physics',
            designation: 'Associate Professor',
            salary: 71000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [28, 30, 32],
            createdAt: new Date('2023-09-10').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 13,
            name: 'Dr. Alex Martinez',
            email: 'alex.martinez@university.edu',
            department: 'Physics',
            designation: 'Assistant Professor',
            salary: 55000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [33, 34],
            createdAt: new Date('2023-10-05').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        // Chemistry Department - 3 faculty
        {
            userId: 14,
            name: 'Dr. Susan Davis',
            email: 'susan.davis@university.edu',
            department: 'Chemistry',
            designation: 'Professor',
            salary: 89000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [35, 37, 39, 41],
            createdAt: new Date('2023-08-30').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 15,
            name: 'Dr. Kevin Taylor',
            email: 'kevin.taylor@university.edu',
            department: 'Chemistry',
            designation: 'Associate Professor',
            salary: 73000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [36, 38, 40],
            createdAt: new Date('2023-09-12').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            userId: 16,
            name: 'Dr. Amy Johnson',
            email: 'amy.johnson@university.edu',
            department: 'Chemistry',
            designation: 'Assistant Professor',
            salary: 59000.00,
            lastPaymentDate: new Date('2024-01-31').toISOString(),
            assignedCourses: [42, 43],
            createdAt: new Date('2023-10-15').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
    ];

    await db.insert(faculty).values(sampleFaculty);
    
    console.log('✅ Faculty seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});