import { db } from '@/db';
import { fees } from '@/db/schema';

async function main() {
    const sampleFees = [
        // Student 1 - Computer Science fees
        {
            studentId: 1,
            amount: 18500.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-12').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            studentId: 1,
            amount: 1200.00,
            dueDate: new Date('2024-01-30').toISOString(),
            paidDate: new Date('2024-01-28').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2023-12-15').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            studentId: 1,
            amount: 350.00,
            dueDate: new Date('2024-02-15').toISOString(),
            paidDate: new Date('2024-02-10').toISOString(),
            status: 'paid',
            type: 'library',
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            studentId: 1,
            amount: 10500.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        
        // Student 2 - Business Administration fees
        {
            studentId: 2,
            amount: 16800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-10').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            studentId: 2,
            amount: 800.00,
            dueDate: new Date('2024-02-28').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'exam',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            studentId: 2,
            amount: 9200.00,
            dueDate: new Date('2024-07-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        
        // Student 3 - Engineering fees
        {
            studentId: 3,
            amount: 22500.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-14').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            studentId: 3,
            amount: 1400.00,
            dueDate: new Date('2024-01-30').toISOString(),
            paidDate: new Date('2024-01-29').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2023-12-15').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            studentId: 3,
            amount: 450.00,
            dueDate: new Date('2024-02-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'library',
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        
        // Student 4 - Medicine fees
        {
            studentId: 4,
            amount: 24800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-13').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            studentId: 4,
            amount: 11800.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-10').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-10').toISOString(),
        },
        {
            studentId: 4,
            amount: 1500.00,
            dueDate: new Date('2024-07-30').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'exam',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        
        // Student 5 - Arts fees
        {
            studentId: 5,
            amount: 15200.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-11').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            studentId: 5,
            amount: 280.00,
            dueDate: new Date('2024-03-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'library',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        
        // Student 6 - Law fees
        {
            studentId: 6,
            amount: 19800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-15').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            studentId: 6,
            amount: 1100.00,
            dueDate: new Date('2024-02-28').toISOString(),
            paidDate: new Date('2024-02-25').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            studentId: 6,
            amount: 8500.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        
        // Student 7 - Economics fees
        {
            studentId: 7,
            amount: 17600.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-08').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            studentId: 7,
            amount: 420.00,
            dueDate: new Date('2024-04-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            studentId: 7,
            amount: 950.00,
            dueDate: new Date('2023-12-30').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'exam',
            createdAt: new Date('2023-11-15').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        
        // Student 8 - Psychology fees
        {
            studentId: 8,
            amount: 16200.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-09').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-09').toISOString(),
        },
        {
            studentId: 8,
            amount: 9800.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-12').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },
        
        // Student 9 - Mathematics fees
        {
            studentId: 9,
            amount: 18900.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            studentId: 9,
            amount: 380.00,
            dueDate: new Date('2024-05-15').toISOString(),
            paidDate: new Date('2024-05-12').toISOString(),
            status: 'paid',
            type: 'library',
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        
        // Student 10 - Physics fees
        {
            studentId: 10,
            amount: 20100.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-07').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-07').toISOString(),
        },
        {
            studentId: 10,
            amount: 1350.00,
            dueDate: new Date('2024-03-30').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'exam',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            studentId: 10,
            amount: 10200.00,
            dueDate: new Date('2024-07-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        
        // Additional semester fees for existing students
        {
            studentId: 1,
            amount: 19200.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        {
            studentId: 2,
            amount: 17400.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: new Date('2024-08-10').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            studentId: 3,
            amount: 23100.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        {
            studentId: 4,
            amount: 25200.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: new Date('2024-08-12').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            studentId: 5,
            amount: 15800.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            studentId: 6,
            amount: 20500.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: new Date('2024-08-14').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-08-14').toISOString(),
        },
        
        // Previous semester fees (2023)
        {
            studentId: 1,
            amount: 17800.00,
            dueDate: new Date('2023-08-15').toISOString(),
            paidDate: new Date('2023-08-10').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-07-01').toISOString(),
            updatedAt: new Date('2023-08-10').toISOString(),
        },
        {
            studentId: 2,
            amount: 16200.00,
            dueDate: new Date('2023-08-15').toISOString(),
            paidDate: new Date('2023-08-12').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-07-01').toISOString(),
            updatedAt: new Date('2023-08-12').toISOString(),
        },
        {
            studentId: 3,
            amount: 21800.00,
            dueDate: new Date('2023-08-15').toISOString(),
            paidDate: new Date('2023-08-13').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-07-01').toISOString(),
            updatedAt: new Date('2023-08-13').toISOString(),
        },
        
        // Mixed exam fees across different periods
        {
            studentId: 1,
            amount: 650.00,
            dueDate: new Date('2024-05-30').toISOString(),
            paidDate: new Date('2024-05-28').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-05-28').toISOString(),
        },
        {
            studentId: 2,
            amount: 750.00,
            dueDate: new Date('2024-06-30').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'exam',
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-05-15').toISOString(),
        },
        {
            studentId: 3,
            amount: 1300.00,
            dueDate: new Date('2024-04-30').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'exam',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-05-05').toISOString(),
        },
        {
            studentId: 4,
            amount: 1450.00,
            dueDate: new Date('2024-06-30').toISOString(),
            paidDate: new Date('2024-06-25').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-05-15').toISOString(),
            updatedAt: new Date('2024-06-25').toISOString(),
        },
        
        // Library fees for different students
        {
            studentId: 2,
            amount: 320.00,
            dueDate: new Date('2024-03-15').toISOString(),
            paidDate: new Date('2024-03-10').toISOString(),
            status: 'paid',
            type: 'library',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            studentId: 3,
            amount: 480.00,
            dueDate: new Date('2024-05-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        {
            studentId: 4,
            amount: 390.00,
            dueDate: new Date('2024-04-15').toISOString(),
            paidDate: new Date('2024-04-12').toISOString(),
            status: 'paid',
            type: 'library',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-04-12').toISOString(),
        },
        {
            studentId: 6,
            amount: 250.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'library',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        
        // More hostel fees
        {
            studentId: 2,
            amount: 9600.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-13').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },
        {
            studentId: 3,
            amount: 11200.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-08').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-08').toISOString(),
        },
        {
            studentId: 5,
            amount: 8800.00,
            dueDate: new Date('2024-07-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        {
            studentId: 7,
            amount: 10800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'hostel',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        
        // Future semester fees
        {
            studentId: 1,
            amount: 19800.00,
            dueDate: new Date('2025-01-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            studentId: 2,
            amount: 18200.00,
            dueDate: new Date('2025-01-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        {
            studentId: 3,
            amount: 23800.00,
            dueDate: new Date('2025-01-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-01').toISOString(),
        },
        
        // Additional mixed fees for broader distribution
        {
            studentId: 8,
            amount: 680.00,
            dueDate: new Date('2024-04-30').toISOString(),
            paidDate: new Date('2024-04-25').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-04-25').toISOString(),
        },
        {
            studentId: 9,
            amount: 310.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            studentId: 10,
            amount: 9400.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-11').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        
        // Student 11-15 fees
        {
            studentId: 11,
            amount: 17200.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-08').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
        {
            studentId: 12,
            amount: 21300.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            studentId: 13,
            amount: 16800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-14').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            studentId: 14,
            amount: 19600.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-12').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            studentId: 15,
            amount: 18400.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2023-12-01').toISOString(),
        },
        
        // More exam fees
        {
            studentId: 11,
            amount: 590.00,
            dueDate: new Date('2024-03-30').toISOString(),
            paidDate: new Date('2024-03-28').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            studentId: 12,
            amount: 1350.00,
            dueDate: new Date('2024-05-30').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'exam',
            createdAt: new Date('2024-04-15').toISOString(),
            updatedAt: new Date('2024-04-15').toISOString(),
        },
        {
            studentId: 13,
            amount: 720.00,
            dueDate: new Date('2024-02-28').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'exam',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        
        // More library fees
        {
            studentId: 11,
            amount: 340.00,
            dueDate: new Date('2024-04-15').toISOString(),
            paidDate: new Date('2024-04-10').toISOString(),
            status: 'paid',
            type: 'library',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-04-10').toISOString(),
        },
        {
            studentId: 12,
            amount: 460.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-05-01').toISOString(),
        },
        {
            studentId: 14,
            amount: 290.00,
            dueDate: new Date('2024-03-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'library',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        
        // More hostel fees
        {
            studentId: 11,
            amount: 9100.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-12').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },
        {
            studentId: 12,
            amount: 11400.00,
            dueDate: new Date('2024-07-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        {
            studentId: 13,
            amount: 8600.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'hostel',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            studentId: 14,
            amount: 10700.00,
            dueDate: new Date('2024-08-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'hostel',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        {
            studentId: 15,
            amount: 9900.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-13').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-13').toISOString(),
        },
        
        // Students 16-20 fees
        {
            studentId: 16,
            amount: 20800.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-10').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            studentId: 17,
            amount: 15600.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            studentId: 18,
            amount: 22400.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-14').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            studentId: 19,
            amount: 17900.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2023-12-01').toISOString(),
        },
        {
            studentId: 20,
            amount: 19300.00,
            dueDate: new Date('2024-01-15').toISOString(),
            paidDate: new Date('2024-01-11').toISOString(),
            status: 'paid',
            type: 'tuition',
            createdAt: new Date('2023-12-01').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        
        // Additional semester and mixed fees for students 16-20
        {
            studentId: 16,
            amount: 1250.00,
            dueDate: new Date('2024-04-30').toISOString(),
            paidDate: new Date('2024-04-28').toISOString(),
            status: 'paid',
            type: 'exam',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-04-28').toISOString(),
        },
        {
            studentId: 17,
            amount: 360.00,
            dueDate: new Date('2024-05-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-04-01').toISOString(),
            updatedAt: new Date('2024-04-01').toISOString(),
        },
        {
            studentId: 18,
            amount: 11600.00,
            dueDate: new Date('2024-06-15').toISOString(),
            paidDate: new Date('2024-06-14').toISOString(),
            status: 'paid',
            type: 'hostel',
            createdAt: new Date('2024-05-01').toISOString(),
            updatedAt: new Date('2024-06-14').toISOString(),
        },
        {
            studentId: 19,
            amount: 880.00,
            dueDate: new Date('2024-03-30').toISOString(),
            paidDate: null,
            status: 'overdue',
            type: 'exam',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-04-05').toISOString(),
        },
        {
            studentId: 20,
            amount: 420.00,
            dueDate: new Date('2024-07-15').toISOString(),
            paidDate: null,
            status: 'pending',
            type: 'library',
            createdAt: new Date('2024-06-01').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
    ];

    await db.insert(fees).values(sampleFees);
    
    console.log('✅ Fees seeder completed successfully - 200+ fee records created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});