import { db } from '@/db';
import { students } from '@/db/schema';

async function main() {
    const sampleStudents = [
        // Computer Science Students (20)
        {
            userId: 1,
            name: 'John Smith',
            email: 'john.smith@university.edu',
            course: 'Computer Science',
            year: 1,
            balance: 0,
            phone: '+1-555-0101',
            address: '123 Elm Street, Springfield, IL 62701',
            enrollmentDate: new Date('2024-08-15').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        },
        {
            userId: 2,
            name: 'Emily Johnson',
            email: 'emily.johnson@university.edu',
            course: 'Computer Science',
            year: 2,
            balance: 1250.50,
            phone: '+1-555-0102',
            address: '456 Oak Avenue, Madison, WI 53703',
            enrollmentDate: new Date('2023-08-20').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-20').toISOString(),
            updatedAt: new Date('2023-08-20').toISOString(),
        },
        {
            userId: 3,
            name: 'Michael Davis',
            email: 'michael.davis@university.edu',
            course: 'Computer Science',
            year: 3,
            balance: 2100.00,
            phone: '+1-555-0103',
            address: '789 Pine Road, Austin, TX 78701',
            enrollmentDate: new Date('2022-08-25').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-25').toISOString(),
            updatedAt: new Date('2022-08-25').toISOString(),
        },
        {
            userId: 4,
            name: 'Sarah Wilson',
            email: 'sarah.wilson@university.edu',
            course: 'Computer Science',
            year: 4,
            balance: 0,
            phone: '+1-555-0104',
            address: '321 Maple Lane, Denver, CO 80202',
            enrollmentDate: new Date('2021-08-30').toISOString(),
            status: 'active',
            createdAt: new Date('2021-08-30').toISOString(),
            updatedAt: new Date('2021-08-30').toISOString(),
        },
        {
            userId: 5,
            name: 'David Brown',
            email: 'david.brown@university.edu',
            course: 'Computer Science',
            year: 2,
            balance: 750.75,
            phone: '+1-555-0105',
            address: '654 Cedar Street, Portland, OR 97201',
            enrollmentDate: new Date('2023-08-18').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-18').toISOString(),
            updatedAt: new Date('2023-08-18').toISOString(),
        },
        {
            userId: 6,
            name: 'Jessica Miller',
            email: 'jessica.miller@university.edu',
            course: 'Computer Science',
            year: 1,
            balance: 3200.00,
            phone: '+1-555-0106',
            address: '987 Birch Boulevard, Seattle, WA 98101',
            enrollmentDate: new Date('2024-08-12').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-12').toISOString(),
            updatedAt: new Date('2024-08-12').toISOString(),
        },
        {
            userId: 7,
            name: 'Christopher Garcia',
            email: 'christopher.garcia@university.edu',
            course: 'Computer Science',
            year: 3,
            balance: 0,
            phone: '+1-555-0107',
            address: '147 Willow Way, Miami, FL 33101',
            enrollmentDate: new Date('2022-08-22').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-22').toISOString(),
            updatedAt: new Date('2022-08-22').toISOString(),
        },
        {
            userId: 8,
            name: 'Amanda Martinez',
            email: 'amanda.martinez@university.edu',
            course: 'Computer Science',
            year: 4,
            balance: 1800.25,
            phone: '+1-555-0108',
            address: '258 Spruce Circle, Boston, MA 02101',
            enrollmentDate: new Date('2021-08-28').toISOString(),
            status: 'graduated',
            createdAt: new Date('2021-08-28').toISOString(),
            updatedAt: new Date('2021-08-28').toISOString(),
        },
        {
            userId: 9,
            name: 'Ryan Anderson',
            email: 'ryan.anderson@university.edu',
            course: 'Computer Science',
            year: 2,
            balance: 950.00,
            phone: '+1-555-0109',
            address: '369 Ash Drive, Phoenix, AZ 85001',
            enrollmentDate: new Date('2023-08-16').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-16').toISOString(),
            updatedAt: new Date('2023-08-16').toISOString(),
        },
        {
            userId: 10,
            name: 'Nicole Taylor',
            email: 'nicole.taylor@university.edu',
            course: 'Computer Science',
            year: 1,
            balance: 2500.50,
            phone: '+1-555-0110',
            address: '741 Poplar Place, Las Vegas, NV 89101',
            enrollmentDate: new Date('2024-08-14').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-14').toISOString(),
            updatedAt: new Date('2024-08-14').toISOString(),
        },
        {
            userId: 11,
            name: 'Kevin Thomas',
            email: 'kevin.thomas@university.edu',
            course: 'Computer Science',
            year: 3,
            balance: 0,
            phone: '+1-555-0111',
            address: '852 Hickory Hill, Atlanta, GA 30301',
            enrollmentDate: new Date('2022-08-24').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-24').toISOString(),
            updatedAt: new Date('2022-08-24').toISOString(),
        },
        {
            userId: 12,
            name: 'Lauren Jackson',
            email: 'lauren.jackson@university.edu',
            course: 'Computer Science',
            year: 4,
            balance: 1450.75,
            phone: '+1-555-0112',
            address: '963 Walnut Street, Nashville, TN 37201',
            enrollmentDate: new Date('2021-09-01').toISOString(),
            status: 'active',
            createdAt: new Date('2021-09-01').toISOString(),
            updatedAt: new Date('2021-09-01').toISOString(),
        },
        {
            userId: 13,
            name: 'Brandon White',
            email: 'brandon.white@university.edu',
            course: 'Computer Science',
            year: 1,
            balance: 3750.00,
            phone: '+1-555-0113',
            address: '159 Chestnut Court, San Diego, CA 92101',
            enrollmentDate: new Date('2024-08-10').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-08-10').toISOString(),
        },
        {
            userId: 14,
            name: 'Stephanie Harris',
            email: 'stephanie.harris@university.edu',
            course: 'Computer Science',
            year: 2,
            balance: 0,
            phone: '+1-555-0114',
            address: '357 Beech Avenue, Charlotte, NC 28201',
            enrollmentDate: new Date('2023-08-19').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-19').toISOString(),
            updatedAt: new Date('2023-08-19').toISOString(),
        },
        {
            userId: 15,
            name: 'Jonathan Clark',
            email: 'jonathan.clark@university.edu',
            course: 'Computer Science',
            year: 3,
            balance: 1100.00,
            phone: '+1-555-0115',
            address: '468 Sycamore Street, Detroit, MI 48201',
            enrollmentDate: new Date('2022-08-26').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-26').toISOString(),
            updatedAt: new Date('2022-08-26').toISOString(),
        },
        {
            userId: 16,
            name: 'Megan Lewis',
            email: 'megan.lewis@university.edu',
            course: 'Computer Science',
            year: 4,
            balance: 2300.25,
            phone: '+1-555-0116',
            address: '579 Dogwood Drive, Houston, TX 77001',
            enrollmentDate: new Date('2021-08-27').toISOString(),
            status: 'inactive',
            createdAt: new Date('2021-08-27').toISOString(),
            updatedAt: new Date('2021-08-27').toISOString(),
        },
        {
            userId: 17,
            name: 'Tyler Robinson',
            email: 'tyler.robinson@university.edu',
            course: 'Computer Science',
            year: 2,
            balance: 850.50,
            phone: '+1-555-0117',
            address: '681 Redwood Road, San Francisco, CA 94101',
            enrollmentDate: new Date('2023-08-17').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-17').toISOString(),
            updatedAt: new Date('2023-08-17').toISOString(),
        },
        {
            userId: 18,
            name: 'Kimberly Walker',
            email: 'kimberly.walker@university.edu',
            course: 'Computer Science',
            year: 1,
            balance: 0,
            phone: '+1-555-0118',
            address: '792 Magnolia Manor, New Orleans, LA 70112',
            enrollmentDate: new Date('2024-08-13').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-13').toISOString(),
            updatedAt: new Date('2024-08-13').toISOString(),
        },
        {
            userId: 19,
            name: 'Justin Hall',
            email: 'justin.hall@university.edu',
            course: 'Computer Science',
            year: 3,
            balance: 1950.00,
            phone: '+1-555-0119',
            address: '814 Elm Grove, Pittsburgh, PA 15201',
            enrollmentDate: new Date('2022-08-23').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-23').toISOString(),
            updatedAt: new Date('2022-08-23').toISOString(),
        },
        {
            userId: 20,
            name: 'Rachel Allen',
            email: 'rachel.allen@university.edu',
            course: 'Computer Science',
            year: 4,
            balance: 675.75,
            phone: '+1-555-0120',
            address: '925 Cedar Crest, Baltimore, MD 21201',
            enrollmentDate: new Date('2021-08-29').toISOString(),
            status: 'active',
            createdAt: new Date('2021-08-29').toISOString(),
            updatedAt: new Date('2021-08-29').toISOString(),
        },

        // Mathematics Students (15)
        {
            userId: 21,
            name: 'Alexander Young',
            email: 'alexander.young@university.edu',
            course: 'Mathematics',
            year: 1,
            balance: 1500.00,
            phone: '+1-555-0121',
            address: '136 Pine Valley, Columbus, OH 43215',
            enrollmentDate: new Date('2024-08-11').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-11').toISOString(),
            updatedAt: new Date('2024-08-11').toISOString(),
        },
        {
            userId: 22,
            name: 'Victoria King',
            email: 'victoria.king@university.edu',
            course: 'Mathematics',
            year: 2,
            balance: 0,
            phone: '+1-555-0122',
            address: '247 Maple Ridge, Memphis, TN 38103',
            enrollmentDate: new Date('2023-08-21').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-21').toISOString(),
            updatedAt: new Date('2023-08-21').toISOString(),
        },
        {
            userId: 23,
            name: 'Nathan Wright',
            email: 'nathan.wright@university.edu',
            course: 'Mathematics',
            year: 3,
            balance: 2750.25,
            phone: '+1-555-0123',
            address: '358 Oak Hill, Milwaukee, WI 53202',
            enrollmentDate: new Date('2022-08-27').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-27').toISOString(),
            updatedAt: new Date('2022-08-27').toISOString(),
        },
        {
            userId: 24,
            name: 'Samantha Lopez',
            email: 'samantha.lopez@university.edu',
            course: 'Mathematics',
            year: 4,
            balance: 1200.50,
            phone: '+1-555-0124',
            address: '469 Birch Creek, Kansas City, MO 64108',
            enrollmentDate: new Date('2021-09-02').toISOString(),
            status: 'graduated',
            createdAt: new Date('2021-09-02').toISOString(),
            updatedAt: new Date('2021-09-02').toISOString(),
        },
        {
            userId: 25,
            name: 'Zachary Hill',
            email: 'zachary.hill@university.edu',
            course: 'Mathematics',
            year: 1,
            balance: 0,
            phone: '+1-555-0125',
            address: '571 Willow Creek, Tucson, AZ 85701',
            enrollmentDate: new Date('2024-08-16').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-16').toISOString(),
            updatedAt: new Date('2024-08-16').toISOString(),
        },
        {
            userId: 26,
            name: 'Brittany Green',
            email: 'brittany.green@university.edu',
            course: 'Mathematics',
            year: 2,
            balance: 3100.00,
            phone: '+1-555-0126',
            address: '682 Cedar Point, Minneapolis, MN 55401',
            enrollmentDate: new Date('2023-08-22').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-22').toISOString(),
            updatedAt: new Date('2023-08-22').toISOString(),
        },
        {
            userId: 27,
            name: 'Gregory Adams',
            email: 'gregory.adams@university.edu',
            course: 'Mathematics',
            year: 3,
            balance: 875.75,
            phone: '+1-555-0127',
            address: '793 Elm Street, Albuquerque, NM 87101',
            enrollmentDate: new Date('2022-08-28').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-28').toISOString(),
            updatedAt: new Date('2022-08-28').toISOString(),
        },
        {
            userId: 28,
            name: 'Danielle Baker',
            email: 'danielle.baker@university.edu',
            course: 'Mathematics',
            year: 4,
            balance: 0,
            phone: '+1-555-0128',
            address: '815 Pine Forest, Sacramento, CA 95814',
            enrollmentDate: new Date('2021-08-31').toISOString(),
            status: 'active',
            createdAt: new Date('2021-08-31').toISOString(),
            updatedAt: new Date('2021-08-31').toISOString(),
        },
        {
            userId: 29,
            name: 'Jordan Nelson',
            email: 'jordan.nelson@university.edu',
            course: 'Mathematics',
            year: 2,
            balance: 1650.25,
            phone: '+1-555-0129',
            address: '926 Oak Ridge, Salt Lake City, UT 84101',
            enrollmentDate: new Date('2023-08-23').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-23').toISOString(),
            updatedAt: new Date('2023-08-23').toISOString(),
        },
        {
            userId: 30,
            name: 'Chelsea Carter',
            email: 'chelsea.carter@university.edu',
            course: 'Mathematics',
            year: 1,
            balance: 2400.00,
            phone: '+1-555-0130',
            address: '147 Maple Wood, Richmond, VA 23219',
            enrollmentDate: new Date('2024-08-17').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-17').toISOString(),
            updatedAt: new Date('2024-08-17').toISOString(),
        },
        {
            userId: 31,
            name: 'Marcus Mitchell',
            email: 'marcus.mitchell@university.edu',
            course: 'Mathematics',
            year: 3,
            balance: 0,
            phone: '+1-555-0131',
            address: '258 Birch Lane, Oklahoma City, OK 73102',
            enrollmentDate: new Date('2022-08-29').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-29').toISOString(),
            updatedAt: new Date('2022-08-29').toISOString(),
        },
        {
            userId: 32,
            name: 'Jasmine Perez',
            email: 'jasmine.perez@university.edu',
            course: 'Mathematics',
            year: 4,
            balance: 1350.50,
            phone: '+1-555-0132',
            address: '369 Cedar Heights, Louisville, KY 40202',
            enrollmentDate: new Date('2021-09-03').toISOString(),
            status: 'inactive',
            createdAt: new Date('2021-09-03').toISOString(),
            updatedAt: new Date('2021-09-03').toISOString(),
        },
        {
            userId: 33,
            name: 'Cameron Roberts',
            email: 'cameron.roberts@university.edu',
            course: 'Mathematics',
            year: 2,
            balance: 775.25,
            phone: '+1-555-0133',
            address: '471 Willow Park, Buffalo, NY 14201',
            enrollmentDate: new Date('2023-08-24').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-24').toISOString(),
            updatedAt: new Date('2023-08-24').toISOString(),
        },
        {
            userId: 34,
            name: 'Alexis Turner',
            email: 'alexis.turner@university.edu',
            course: 'Mathematics',
            year: 1,
            balance: 2950.00,
            phone: '+1-555-0134',
            address: '582 Pine Meadow, Hartford, CT 06103',
            enrollmentDate: new Date('2024-08-18').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-18').toISOString(),
            updatedAt: new Date('2024-08-18').toISOString(),
        },
        {
            userId: 35,
            name: 'Derek Phillips',
            email: 'derek.phillips@university.edu',
            course: 'Mathematics',
            year: 3,
            balance: 1125.75,
            phone: '+1-555-0135',
            address: '693 Oak Valley, Honolulu, HI 96813',
            enrollmentDate: new Date('2022-08-30').toISOString(),
            status: 'active',
            createdAt: new Date('2022-08-30').toISOString(),
            updatedAt: new Date('2022-08-30').toISOString(),
        },

        // Physics Students (10)
        {
            userId: 36,
            name: 'Matthew Campbell',
            email: 'matthew.campbell@university.edu',
            course: 'Physics',
            year: 1,
            balance: 1800.00,
            phone: '+1-555-0136',
            address: '714 Elm Park, Anchorage, AK 99501',
            enrollmentDate: new Date('2024-08-19').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-19').toISOString(),
            updatedAt: new Date('2024-08-19').toISOString(),
        },
        {
            userId: 37,
            name: 'Kayla Parker',
            email: 'kayla.parker@university.edu',
            course: 'Physics',
            year: 2,
            balance: 0,
            phone: '+1-555-0137',
            address: '825 Maple Grove, Portland, ME 04101',
            enrollmentDate: new Date('2023-08-25').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-25').toISOString(),
            updatedAt: new Date('2023-08-25').toISOString(),
        },
        {
            userId: 38,
            name: 'Trevor Evans',
            email: 'trevor.evans@university.edu',
            course: 'Physics',
            year: 3,
            balance: 2200.50,
            phone: '+1-555-0138',
            address: '936 Pine Hill, Burlington, VT 05401',
            enrollmentDate: new Date('2022-09-01').toISOString(),
            status: 'active',
            createdAt: new Date('2022-09-01').toISOString(),
            updatedAt: new Date('2022-09-01').toISOString(),
        },
        {
            userId: 39,
            name: 'Andrea Edwards',
            email: 'andrea.edwards@university.edu',
            course: 'Physics',
            year: 4,
            balance: 950.25,
            phone: '+1-555-0139',
            address: '147 Cedar Brook, Des Moines, IA 50309',
            enrollmentDate: new Date('2021-09-04').toISOString(),
            status: 'graduated',
            createdAt: new Date('2021-09-04').toISOString(),
            updatedAt: new Date('2021-09-04').toISOString(),
        },
        {
            userId: 40,
            name: 'Corey Collins',
            email: 'corey.collins@university.edu',
            course: 'Physics',
            year: 2,
            balance: 1475.00,
            phone: '+1-555-0140',
            address: '258 Birch Ridge, Little Rock, AR 72201',
            enrollmentDate: new Date('2023-08-26').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-26').toISOString(),
            updatedAt: new Date('2023-08-26').toISOString(),
        },
        {
            userId: 41,
            name: 'Monique Stewart',
            email: 'monique.stewart@university.edu',
            course: 'Physics',
            year: 1,
            balance: 0,
            phone: '+1-555-0141',
            address: '369 Willow Glen, Jackson, MS 39201',
            enrollmentDate: new Date('2024-08-20').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-20').toISOString(),
            updatedAt: new Date('2024-08-20').toISOString(),
        },
        {
            userId: 42,
            name: 'Austin Sanchez',
            email: 'austin.sanchez@university.edu',
            course: 'Physics',
            year: 3,
            balance: 3200.75,
            phone: '+1-555-0142',
            address: '471 Oak Creek, Boise, ID 83702',
            enrollmentDate: new Date('2022-09-02').toISOString(),
            status: 'active',
            createdAt: new Date('2022-09-02').toISOString(),
            updatedAt: new Date('2022-09-02').toISOString(),
        },
        {
            userId: 43,
            name: 'Cassandra Morris',
            email: 'cassandra.morris@university.edu',
            course: 'Physics',
            year: 4,
            balance: 725.50,
            phone: '+1-555-0143',
            address: '582 Pine Summit, Charleston, WV 25301',
            enrollmentDate: new Date('2021-09-05').toISOString(),
            status: 'active',
            createdAt: new Date('2021-09-05').toISOString(),
            updatedAt: new Date('2021-09-05').toISOString(),
        },
        {
            userId: 44,
            name: 'Blake Rogers',
            email: 'blake.rogers@university.edu',
            course: 'Physics',
            year: 2,
            balance: 1825.25,
            phone: '+1-555-0144',
            address: '693 Elm Ridge, Montpelier, VT 05602',
            enrollmentDate: new Date('2023-08-27').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-27').toISOString(),
            updatedAt: new Date('2023-08-27').toISOString(),
        },
        {
            userId: 45,
            name: 'Vanessa Reed',
            email: 'vanessa.reed@university.edu',
            course: 'Physics',
            year: 1,
            balance: 2675.00,
            phone: '+1-555-0145',
            address: '714 Maple Crest, Pierre, SD 57501',
            enrollmentDate: new Date('2024-08-21').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-21').toISOString(),
            updatedAt: new Date('2024-08-21').toISOString(),
        },

        // Chemistry Students (8)
        {
            userId: 46,
            name: 'Ethan Cook',
            email: 'ethan.cook@university.edu',
            course: 'Chemistry',
            year: 1,
            balance: 1350.00,
            phone: '+1-555-0146',
            address: '825 Cedar Point, Bismarck, ND 58501',
            enrollmentDate: new Date('2024-08-22').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-22').toISOString(),
            updatedAt: new Date('2024-08-22').toISOString(),
        },
        {
            userId: 47,
            name: 'Gabrielle Bailey',
            email: 'gabrielle.bailey@university.edu',
            course: 'Chemistry',
            year: 2,
            balance: 0,
            phone: '+1-555-0147',
            address: '936 Pine Valley, Helena, MT 59601',
            enrollmentDate: new Date('2023-08-28').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-28').toISOString(),
            updatedAt: new Date('2023-08-28').toISOString(),
        },
        {
            userId: 48,
            name: 'Ian Rivera',
            email: 'ian.rivera@university.edu',
            course: 'Chemistry',
            year: 3,
            balance: 2150.75,
            phone: '+1-555-0148',
            address: '147 Birch Wood, Cheyenne, WY 82001',
            enrollmentDate: new Date('2022-09-03').toISOString(),
            status: 'active',
            createdAt: new Date('2022-09-03').toISOString(),
            updatedAt: new Date('2022-09-03').toISOString(),
        },
        {
            userId: 49,
            name: 'Natalie Cooper',
            email: 'natalie.cooper@university.edu',
            course: 'Chemistry',
            year: 4,
            balance: 875.25,
            phone: '+1-555-0149',
            address: '258 Oak Hollow, Dover, DE 19901',
            enrollmentDate: new Date('2021-09-06').toISOString(),
            status: 'graduated',
            createdAt: new Date('2021-09-06').toISOString(),
            updatedAt: new Date('2021-09-06').toISOString(),
        },
        {
            userId: 50,
            name: 'Sean Richardson',
            email: 'sean.richardson@university.edu',
            course: 'Chemistry',
            year: 2,
            balance: 1925.50,
            phone: '+1-555-0150',
            address: '369 Willow Ridge, Frankfort, KY 40601',
            enrollmentDate: new Date('2023-08-29').toISOString(),
            status: 'active',
            createdAt: new Date('2023-08-29').toISOString(),
            updatedAt: new Date('2023-08-29').toISOString(),
        },
        {
            userId: 51,
            name: 'Olivia Cox',
            email: 'olivia.cox@university.edu',
            course: 'Chemistry',
            year: 1,
            balance: 0,
            phone: '+1-555-0151',
            address: '471 Cedar Glen, Augusta, ME 04330',
            enrollmentDate: new Date('2024-08-23').toISOString(),
            status: 'active',
            createdAt: new Date('2024-08-23').toISOString(),
            updatedAt: new Date('2024-08-23').toISOString(),
        },
        {
            userId: 52,
            name: 'Lucas Ward',
            email: 'lucas.ward@university.edu',
            course: 'Chemistry',
            year: 3,
            balance: 2800.00,
            phone: '+1-555-0152',
            address: '582 Pine Grove, Annapolis, MD 21401',
            enrollmentDate: new Date('2022-09-04').toISOString(),
            status: 'inactive',
            createdAt: new Date('2022-09-04').toISOString(),
            updatedAt: new Date('2022-09-04').toISOString(),
        },
        {
            userId: 53,
            name: 'Isabella Torres',
            email: 'isabella.torres@university.edu',
            course: 'Chemistry',
            year: 4,
            balance: 1425.75,
            phone: '+1-555-0153',
            address: '693 Maple Heights, Trenton, NJ 08608',
            enrollmentDate: new Date('2021-09-07').toISOString(),
            status: 'active',
            createdAt: new Date('2021-09-07').toISOString(),
            updatedAt: new Date('2021-09-07').toISOString(),
        }
    ];

    await db.insert(students).values(sampleStudents);
    
    console.log('✅ Students seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});