import { db } from '@/db';
import { users } from '@/db/schema';

async function main() {
    const sampleUsers = [
        // Students (50+ users)
        {
            email: 'john.anderson@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'John Anderson',
            role: 'student',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            email: 'sarah.johnson@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Sarah Johnson',
            role: 'student',
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            email: 'michael.chen@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Michael Chen',
            role: 'student',
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            email: 'emily.williams@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Emily Williams',
            role: 'student',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            email: 'david.rodriguez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'David Rodriguez',
            role: 'student',
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            email: 'jessica.brown@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Jessica Brown',
            role: 'student',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            email: 'alex.thompson@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Alex Thompson',
            role: 'student',
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            email: 'priya.patel@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Priya Patel',
            role: 'student',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            email: 'ryan.davis@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Ryan Davis',
            role: 'student',
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            email: 'olivia.martinez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Olivia Martinez',
            role: 'student',
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            email: 'james.garcia@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'James Garcia',
            role: 'student',
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            email: 'sophia.kim@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Sophia Kim',
            role: 'student',
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            email: 'connor.white@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Connor White',
            role: 'student',
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            email: 'maya.singh@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Maya Singh',
            role: 'student',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            email: 'daniel.lee@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Daniel Lee',
            role: 'student',
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            email: 'natalie.wilson@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Natalie Wilson',
            role: 'student',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            email: 'ethan.taylor@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Ethan Taylor',
            role: 'student',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            email: 'aisha.ahmed@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Aisha Ahmed',
            role: 'student',
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            email: 'liam.miller@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Liam Miller',
            role: 'student',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            email: 'zoe.harris@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Zoe Harris',
            role: 'student',
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            email: 'noah.clark@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Noah Clark',
            role: 'student',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            email: 'isabella.rodriguez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Isabella Rodriguez',
            role: 'student',
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            email: 'mason.lewis@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Mason Lewis',
            role: 'student',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            email: 'ava.walker@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Ava Walker',
            role: 'student',
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            email: 'jackson.hall@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Jackson Hall',
            role: 'student',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            email: 'grace.allen@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Grace Allen',
            role: 'student',
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            email: 'lucas.young@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Lucas Young',
            role: 'student',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            email: 'chloe.king@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Chloe King',
            role: 'student',
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            email: 'owen.wright@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Owen Wright',
            role: 'student',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            email: 'lily.lopez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Lily Lopez',
            role: 'student',
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            email: 'caleb.hill@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Caleb Hill',
            role: 'student',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            email: 'mia.scott@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Mia Scott',
            role: 'student',
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        {
            email: 'benjamin.green@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Benjamin Green',
            role: 'student',
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            email: 'aria.adams@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Aria Adams',
            role: 'student',
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            email: 'henry.baker@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Henry Baker',
            role: 'student',
            createdAt: new Date('2024-02-19').toISOString(),
            updatedAt: new Date('2024-02-19').toISOString(),
        },
        {
            email: 'luna.gonzalez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Luna Gonzalez',
            role: 'student',
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            email: 'sebastian.nelson@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Sebastian Nelson',
            role: 'student',
            createdAt: new Date('2024-02-21').toISOString(),
            updatedAt: new Date('2024-02-21').toISOString(),
        },
        {
            email: 'layla.carter@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Layla Carter',
            role: 'student',
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            email: 'grayson.mitchell@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Grayson Mitchell',
            role: 'student',
            createdAt: new Date('2024-02-23').toISOString(),
            updatedAt: new Date('2024-02-23').toISOString(),
        },
        {
            email: 'penelope.perez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Penelope Perez',
            role: 'student',
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            email: 'wyatt.roberts@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Wyatt Roberts',
            role: 'student',
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            email: 'scarlett.turner@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Scarlett Turner',
            role: 'student',
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            email: 'theo.phillips@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Theo Phillips',
            role: 'student',
            createdAt: new Date('2024-02-27').toISOString(),
            updatedAt: new Date('2024-02-27').toISOString(),
        },
        {
            email: 'violet.campbell@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Violet Campbell',
            role: 'student',
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            email: 'julian.parker@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Julian Parker',
            role: 'student',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            email: 'aurora.evans@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Aurora Evans',
            role: 'student',
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        {
            email: 'eli.edwards@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Eli Edwards',
            role: 'student',
            createdAt: new Date('2024-03-03').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            email: 'nova.collins@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Nova Collins',
            role: 'student',
            createdAt: new Date('2024-03-04').toISOString(),
            updatedAt: new Date('2024-03-04').toISOString(),
        },
        {
            email: 'aaron.stewart@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Aaron Stewart',
            role: 'student',
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            email: 'hazel.sanchez@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Hazel Sanchez',
            role: 'student',
            createdAt: new Date('2024-03-06').toISOString(),
            updatedAt: new Date('2024-03-06').toISOString(),
        },
        {
            email: 'nolan.morris@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Nolan Morris',
            role: 'student',
            createdAt: new Date('2024-03-07').toISOString(),
            updatedAt: new Date('2024-03-07').toISOString(),
        },
        {
            email: 'ivy.reed@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Ivy Reed',
            role: 'student',
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            email: 'hunter.cook@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Hunter Cook',
            role: 'student',
            createdAt: new Date('2024-03-09').toISOString(),
            updatedAt: new Date('2024-03-09').toISOString(),
        },
        {
            email: 'elena.bailey@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Elena Bailey',
            role: 'student',
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },

        // Faculty (15+ users)
        {
            email: 'dr.smith@cs.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Robert Smith',
            role: 'faculty',
            createdAt: new Date('2023-08-01').toISOString(),
            updatedAt: new Date('2023-08-01').toISOString(),
        },
        {
            email: 'prof.davis@math.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Maria Davis',
            role: 'faculty',
            createdAt: new Date('2023-08-02').toISOString(),
            updatedAt: new Date('2023-08-02').toISOString(),
        },
        {
            email: 'dr.wilson@physics.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. James Wilson',
            role: 'faculty',
            createdAt: new Date('2023-08-03').toISOString(),
            updatedAt: new Date('2023-08-03').toISOString(),
        },
        {
            email: 'prof.miller@english.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Jennifer Miller',
            role: 'faculty',
            createdAt: new Date('2023-08-04').toISOString(),
            updatedAt: new Date('2023-08-04').toISOString(),
        },
        {
            email: 'dr.brown@chemistry.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Michael Brown',
            role: 'faculty',
            createdAt: new Date('2023-08-05').toISOString(),
            updatedAt: new Date('2023-08-05').toISOString(),
        },
        {
            email: 'prof.johnson@biology.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Sarah Johnson',
            role: 'faculty',
            createdAt: new Date('2023-08-06').toISOString(),
            updatedAt: new Date('2023-08-06').toISOString(),
        },
        {
            email: 'dr.garcia@economics.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Carlos Garcia',
            role: 'faculty',
            createdAt: new Date('2023-08-07').toISOString(),
            updatedAt: new Date('2023-08-07').toISOString(),
        },
        {
            email: 'prof.lee@history.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Lisa Lee',
            role: 'faculty',
            createdAt: new Date('2023-08-08').toISOString(),
            updatedAt: new Date('2023-08-08').toISOString(),
        },
        {
            email: 'dr.taylor@psychology.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. David Taylor',
            role: 'faculty',
            createdAt: new Date('2023-08-09').toISOString(),
            updatedAt: new Date('2023-08-09').toISOString(),
        },
        {
            email: 'prof.martinez@art.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Elena Martinez',
            role: 'faculty',
            createdAt: new Date('2023-08-10').toISOString(),
            updatedAt: new Date('2023-08-10').toISOString(),
        },
        {
            email: 'dr.anderson@engineering.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Thomas Anderson',
            role: 'faculty',
            createdAt: new Date('2023-08-11').toISOString(),
            updatedAt: new Date('2023-08-11').toISOString(),
        },
        {
            email: 'prof.thompson@music.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Rachel Thompson',
            role: 'faculty',
            createdAt: new Date('2023-08-12').toISOString(),
            updatedAt: new Date('2023-08-12').toISOString(),
        },
        {
            email: 'dr.white@business.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Kevin White',
            role: 'faculty',
            createdAt: new Date('2023-08-13').toISOString(),
            updatedAt: new Date('2023-08-13').toISOString(),
        },
        {
            email: 'prof.clark@philosophy.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Prof. Amanda Clark',
            role: 'faculty',
            createdAt: new Date('2023-08-14').toISOString(),
            updatedAt: new Date('2023-08-14').toISOString(),
        },
        {
            email: 'dr.lewis@sociology.college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Christopher Lewis',
            role: 'faculty',
            createdAt: new Date('2023-08-15').toISOString(),
            updatedAt: new Date('2023-08-15').toISOString(),
        },

        // Admin (5+ users)
        {
            email: 'admin.director@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Dr. Patricia Williams',
            role: 'admin',
            createdAt: new Date('2023-07-01').toISOString(),
            updatedAt: new Date('2023-07-01').toISOString(),
        },
        {
            email: 'admin.registrar@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Mark Thompson',
            role: 'admin',
            createdAt: new Date('2023-07-02').toISOString(),
            updatedAt: new Date('2023-07-02').toISOString(),
        },
        {
            email: 'admin.finance@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Linda Rodriguez',
            role: 'admin',
            createdAt: new Date('2023-07-03').toISOString(),
            updatedAt: new Date('2023-07-03').toISOString(),
        },
        {
            email: 'admin.student@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Steven Mitchell',
            role: 'admin',
            createdAt: new Date('2023-07-04').toISOString(),
            updatedAt: new Date('2023-07-04').toISOString(),
        },
        {
            email: 'admin.it@college.edu',
            passwordHash: '$2b$10$rQzJ4kXT.8d5E1vN2mF6G.yQzJ4kXT8d5E1vN2mF6GyQzJ4kXT8d5E',
            name: 'Angela Foster',
            role: 'admin',
            createdAt: new Date('2023-07-05').toISOString(),
            updatedAt: new Date('2023-07-05').toISOString(),
        }
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});